### ISSUE TITLE
Software doing some projection?

### ISSUE THREAD

**Issue by ppKrauss** [paulojraposo/QTM#1]
Hi, the [QTM article](https://pdfs.semanticscholar.org/875e/12ce948012b3eced58c0f1470dba51ef87ef.pdf) uses the Zenithial Ortho Triangular (ZOT) projection... It was implemented in your Python script?

[This page](https://spatialeffects.wordpress.com/gg/qtmqtm/) says that *"QTM facets gradually vary in shape and size; the largest are 1.8 times larger in area than the smallest"*,
there are a correction to obtain an equal-area grid of triangles?

About the ZOT algorithm, what the function name used in your Python  script? 
The QTM article comment that *"Given  the resident octant,  the  process  appends  QTM  codes  to  its  ID  using  an  efficient geometric algorithm called TRILOC, which computes spatial relations in Manhattan space. That  space is a world map projection called Zenithial Ortho Triangular, or ZOT for short"*<br/> "Manhattan distance" and TRILOC are not cited in your source code, they was used there?

**Comment by paulojraposo** [comment]
Hi ppKrauss, Sorry, I'm not sure I understand your questions. 

There's no map projection involved in my script at all; the facet corners are defined on lat/lon coordinates of the sphere, not on a projected map. Of course, the product of the script will be viewed in some projection if you load it on a typical GIS or webmap.

ZOT: do you mean a projection or an algorithm? In either case, I don't recall these, and they're not involved in the script here.

My script makes no effort to correct for area equivalence; Dutton's QTM inherently drifts away from equivalence. There are other DGGS systems that do maintain equivalence.

Hope that helps,
P

**Comment by ppKrauss** [comment]
> Sorry, I'm not sure I understand your questions.

I was looking for a simple QTM  implementation, so `paulojraposo/QTM` seems a good candidate, thanks to publish it in a *git* with MIT License!

> There's no map projection involved in my script at all; the facet corners are defined on lat/lon coordinates of the sphere, not on a projected map.
> ... My script makes no effort to correct for area equivalence.

Hum... I need area equivalence.  Can you suggest any open-source *hierarchical DGG* oriented to  (triangular or quadrilateral) equal area cells?

----

PS: we need something that is open licensed (FOSS) and is not worse than the  [Albers projection for Brazilian territory](https://spatialreference.org/ref/sr-org/albers-conical-equal-area-brazil-sirgas-2000/). For example   [S2 Geometry Library](https://github.com/google/s2geometry) ([variation](https://s2geometry.io/resources/s2cell_statistics.html)) and faces of [H3 Uber](https://github.com/uber/h3) ([distortion](https://observablehq.com/@fil/h3-oddities)/[variation](https://observablehq.com/@nrabinowitz/h3-area-variation)) are not better.   Even [ISEA](https://proj.org/operations/projections/isea.html) seems not better...  Maybe you know some comparative study for DGGS in [land registry](http://2015.index.okfn.org/dataset/land/) or land size applications... Or some  "statistical grid" for population density analysis, but United States Census Bureau  and Brazil IBGE still use Albers.

**Comment by paulojraposo** [comment]
You're welcome about the FOSS script - glad it's useful to you somehow!

Hmm, I don't know of anything that's equal-area besides the things you just mentioned (e.g., ISEA). Does it have to be a fully global DGGS? If you can limit to just part of the Earth (e.g., Brazil), then you can define hierarchical geometries over that that you can keep equivalence in.

As I'm guessing you know, the fundamental problem is that you can't keep a forever-constant shape, i.e., conformality, and area equivalence; areal equivalence will force you to morph the tessera shapes/orientations as you go through zoom levels, and it's just a question of how much is acceptable to your purpose.

**Comment by paulojraposo** [comment]
Also, you probably already know, but look at this FOSS repo by Kevin Sahr (@sahrk): https://github.com/sahrk/DGGRID

**Comment by ppKrauss** [comment]
Thanks @paulojraposo, for the suggestions, good link and all efforts to help!
